### ISSUE TITLE
Too many unused methods

### ISSUE THREAD

**Issue by guseinovmg** [recoilme/tgram#103]
What is author going to do with them?

**Comment by guseinovmg** [comment]
For example methods in file cashe.go. I use Goland IDE, it has greyed unused methods:
![screenshot at 2018-09-24 16-00-06](https://user-images.githubusercontent.com/4104650/45946639-4afff480-c013-11e8-8954-19a8c1909702.png)

**Comment by recoilme** [comment]
it's probably an error in Goland IDE, for example RegisterIPSet used in routers.go (399):
		// add to cache on success
		models.RegisterIPSet(ip)

<img width="901" alt="screen shot 2018-09-24 at 13 08 15" src="https://user-images.githubusercontent.com/417177/45946889-f0f33500-bffa-11e8-9271-b90906ee8068.png">
