### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Fastidious** [recoilme/tgram#112]
I am a little bit lost on how to compile this. I would rather not use *Fresh*, so, which are the simple steps to get it compiled? Thanks!

**Comment by recoilme** [comment]
```
➜  go get ./...
➜  go build or go install
➜  ./tgram or ~/go/bin/tgram
```

**Comment by Fastidious** [comment]
I get:
```
go: warning: "./..." matched no packages
```
Do I need to clone the repository first, and run those within the cloned repository directory?

**Comment by Fastidious** [comment]
Answering to myself:
- Make sure you have the `GOPATH` and `GOBIN` defined.
    `export GOPATH=/path/you/want/to/use`
    `export GOBIN=$GOPATH/bin`
    `export PATH=$PATH:$GOBIN`
- Clone *tgram* and move it to your `GOPATH`.
- Run `go get ./...` within the clone repository.
- Find *tgram* within your `GOBIN`.
