### ISSUE TITLE
avatar

### ISSUE THREAD

**Issue by recoilme** [recoilme/tgram#32]
ex: https://github.com/o1egl/govatar

**Comment by recoilme** [comment]
or may be simple css with avatars from first 2 char in colored circle - like in telegram
<img width="111" alt="screen shot 2018-07-31 at 12 04 53" src="https://user-images.githubusercontent.com/417177/43449767-f7336ef6-94b9-11e8-87fd-36ec354304fd.png">

**Comment by Flameborn** [comment]
I like the two approaches, and I would probably go with the first one, simply because it is more customisable, but it depends on how simple you want it to be.

With the first option, an author could set their gender as well, for example, so avatars could be gender specific. Not sure if we need it to be this complex though.

**Comment by recoilme** [comment]
![](https://raw.githubusercontent.com/o1egl/govatar/master/files/avatars.jpg)
not fan(

more fan: 

https://www.sitepoint.com/examples/primes/lego.html

they all generated from
    2 background image
    2 legs
    2 body
    2 head

May you try to research this?
i may ask a designer or some of the illustrators may be - paint something more pixel art and we may try to generate avatars from it. Via CSS or generate the picture

What do you think?

**Comment by recoilme** [comment]
<img width="199" alt="screen shot 2018-08-14 at 15 50 56" src="https://user-images.githubusercontent.com/417177/44092676-db3fbb0c-9fd9-11e8-8e2d-67c181841c22.png">
i will not happy with avatar like this)

**Comment by Flameborn** [comment]
In this case go with the css version. You are right, it is more zen-like, and we probably don't need gender-based avatars, as much as we do need an avatar ☺️

**Comment by recoilme** [comment]
<img width="204" alt="screen shot 2018-08-14 at 16 07 18" src="https://user-images.githubusercontent.com/417177/44093409-291a8382-9fdc-11e8-8881-52ad526c8be5.png">
very fun for me  https://luciorubeens.github.io/pictogrify/?ref=producthunt
https://github.com/luciorubeens/pictogrify

**Comment by recoilme** [comment]
monster avatar generator 
unpack:
[monstrator.zip](https://github.com/recoilme/tgram/files/2294183/monstrator.zip)
(build for macos)

run - ./govatar generate monster -u recoilme -o avatar.png
place monsters parts pngs in data/monster

**Comment by recoilme** [comment]
<img width="434" alt="screen shot 2018-08-30 at 17 16 31" src="https://user-images.githubusercontent.com/417177/44909221-2e7bdf80-ad27-11e8-8b87-fe095a7d7870.png">
implemented!
