### ISSUE TITLE
https

### ISSUE THREAD

**Issue by recoilme** [recoilme/tgram#41]

**Comment by recoilme** [comment]
add redirect http 2 https?

**Comment by gmemstr** [comment]
Are you using nginx in front of the application? You could use [Let's Encrypt](https://letsencrypt.org/) which will automatically set up the certificates and redirect.

**Comment by recoilme** [comment]
@gmemstr  https://tgr.am/ must work (i don't use nginx, and use letsencrypt)
now https problem - more about clean direct http link from code (image upload for example)
and about automatically redirect from 80 - 443 port
i think it's better for me

**Comment by cornerot** [comment]
You use Caddy, as I see.
Why not just make a  http->https redirect?

**Comment by recoilme** [comment]
@cornerot i will do)

**Comment by recoilme** [comment]
No problem, i just need to clean code before,  i forgot to remove tag help wanted, thank you!

**Comment by cornerot** [comment]
Ok. Пожалуйста!

**Comment by recoilme** [comment]
add auto-update certificate

**Comment by recoilme** [comment]
```
