### ISSUE TITLE
The hostname tgr.am is hardcoded

### ISSUE THREAD

**Issue by Flameborn** [recoilme/tgram#54]
Hello,

I really like the simplicity of this software. Apart from some minor additions, such as an RSS feed, it's very nice.

I would like to start a writers' hub for a small community, possibly widening the target audience as we gain more members.

Currently, the hostname _tgr.am_ is hardcoded, thus it is not possible to host a server on a local network, with an address such as 192.168.0.48.

**Comment by recoilme** [comment]
Hello, @Flameborn 
It must work on another domain (i dont test)  but it very depends on subdomains system, so for running on ip address - try add proxy from 192.168.0.48 to sub.localhost for example. I prefer caddyserver or nginx may be used

**Comment by Flameborn** [comment]
Thank you very much.

Does this mean that Typegram has no landing page, e.g. a page which shows all the available languages, etc?

Also, am I right to assume that it automatically generates a separate site with separate users, posts, etc, for every subdomain, if proxied? e.g. en.domaincom, de.domain.com, etc.

**Comment by recoilme** [comment]
No, you may modify the main page template: https://github.com/recoilme/tgram/blob/master/views/home.html
And hardcode header with language in the proxy, for example. But on localhost, it will start on "sub" subdomain so maybe it doesn't need

**Comment by Flameborn** [comment]
Thank you very much for explaining this. I've managed to set it up and it works nicely!
