### ISSUE TITLE
Reading time

### ISSUE THREAD

**Issue by recoilme** [recoilme/tgram#58]
add words count and reading time on preview pages (all/author) in the compact format.

something like this:

@recoilme 1 min ago                                                                      words: 25 readtime: 1:30

don't show on article page?
don't show if words count == 0

@Flameborn Erion, I may implement it or assign it to you if you want?

**Comment by recoilme** [comment]
oh, it's 1 minute -  I take it)

**Comment by Flameborn** [comment]
I would be happy to implement this. Something like _1m_, _2m_, etc would work I think, for the all/author pages.

Are you planning to have just image posts? If yes, I agree, the reading time should not be there when the word count is zero, sorry I didn't think of that.

**Comment by recoilme** [comment]
It's ok no problem, i do it

**Comment by recoilme** [comment]
<img width="669" alt="screen shot 2018-08-09 at 19 07 31" src="https://user-images.githubusercontent.com/417177/43911186-86285fdc-9c07-11e8-886c-6318bd166df0.png">
