### ISSUE TITLE
Add article grouping

### ISSUE THREAD

**Issue by Flameborn** [recoilme/tgram#64]
I apologise if this is out of scope for TypeGram, as I am not sure about the roadmap.

I was thinking about how best it would be to group articles, based on a certain criteria, such as a common title. This way, an author could have _story title/chapter 1_, _story title/chapter 2_, etc defined.

This could be part of the url, for example: _https://tgr.am/@recoilme/storyTitle/storyChapter_, or _series/Book 1/Chapter 1_, etc.

Besides this, we would also need tags, to be able to list different things, like _Fantasy_, _Non-fiction_, _Scifi_, etc.

This means two additional links for the menu: _list articles by tags_, and _list articles by title_.

For an even faster way of looking for one specific article, a search feature should be added, though I am not sure how efficient this would be with a huge number of articles. We may need a separate DB file for the list of indexes.

If this is needed, this issue should be updated accordingly, to keep track of things. I can implement all or some of these features, I am just putting this out there for discussion.

**Comment by recoilme** [comment]
Grouping of articles is needed,  you right
I start working on it yesterday) 
https://github.com/recoilme/tgram/issues/61

**Comment by recoilme** [comment]
solved in #61
