### ISSUE TITLE
Error when trying to make a post

### ISSUE THREAD

**Issue by zac-garby** [recoilme/tgram#77]
I entered the following information:

<img width="669" alt="screenshot 2018-08-14 at 17 38 50" src="https://user-images.githubusercontent.com/19708658/44105246-001b72d6-9fe9-11e8-9c5a-9168569942f0.png">

And it gave me this error:

<img width="577" alt="screenshot 2018-08-14 at 17 38 58" src="https://user-images.githubusercontent.com/19708658/44105263-0b75714a-9fe9-11e8-9e15-071bc40658e2.png">

**Comment by recoilme** [comment]
tag must be alphanum - likethis11 or somethinglikethis without any space

my english is bad( i don't know how write it more understandable ...

**Comment by zac-garby** [comment]
@recoilme oh i'm stupid lol, didn't read that. Either way, it might be an idea to display the error a bit nicer
